# Generated by Django 3.2.16 on 2022-12-16 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('happening_at', models.DateTimeField()),
                ('photos_link', models.URLField(max_length=999)),
                ('total_cost', models.IntegerField(default=4000)),
            ],
            options={
                'verbose_name_plural': 'Match Days',
                'ordering': ['-happening_at'],
            },
        ),
        migrations.AlterField(
            model_name='place',
            name='map_link',
            field=models.URLField(max_length=999),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('is_going', models.BooleanField(default=False)),
                ('is_not_going', models.BooleanField(default=False)),
                ('match_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.matchday')),
                ('voted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Votes',
            },
        ),
        migrations.AddField(
            model_name='matchday',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.place'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='total_players',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
